/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_MyClass */

#ifndef _Included_org_example_MyClass
#define _Included_org_example_MyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_MyClass
 * Method:    myNativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_MyClass_myNativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
